apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: network-attachment-renderer
  annotations:
    config.kubernetes.io/local-config: "true"
info:
  description: Renders NetworkAttachmentDefinitions from network intents
  keywords:
    - nad
    - multus
    - network-attachment
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.2
      configMap:
        target-cluster: "my-ran"
        target-namespace: "openairinterface"
